// src/lib/encoder.ts

// FULL EXTENDED HTML5 ENTITY LIST (deduped, production-safe)
export const namedEntities: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
  "©": "&copy;",
  "®": "&reg;",
  "€": "&euro;",
  "£": "&pound;",
  "¥": "&yen;",
  "¢": "&cent;",
  "™": "&trade;",
  "§": "&sect;",
  "¶": "&para;",
  "·": "&middot;",
  "×": "&times;",
  "÷": "&divide;",
  "±": "&plusmn;",
  "°": "&deg;",
  "µ": "&micro;",
  "¼": "&frac14;",
  "½": "&frac12;",
  "¾": "&frac34;",
  "—": "&mdash;",
  "–": "&ndash;",
  "•": "&bull;",
  "…": "&hellip;",
  "†": "&dagger;",
  "‡": "&Dagger;",
  "‰": "&permil;",
  "←": "&larr;",
  "↑": "&uarr;",
  "→": "&rarr;",
  "↓": "&darr;",
  "↔": "&harr;",
  "∀": "&forall;",
  "∂": "&part;",
  "∃": "&exist;",
  "∅": "&empty;",
  "∇": "&nabla;",
  "∈": "&isin;",
  "∉": "&notin;",
  "∋": "&ni;",
  "∏": "&prod;",
  "∑": "&sum;",
  "∞": "&infin;",
  "∠": "&ang;",
  "∧": "&and;",
  "∨": "&or;",
  "∩": "&cap;",
  "∪": "&cup;",
  "∫": "&int;",
  "∴": "&there4;",
  "≠": "&ne;",
  "≡": "&equiv;",
  "≤": "&le;",
  "≥": "&ge;",
  "⊂": "&sub;",
  "⊃": "&sup;",
  "⊆": "&sube;",
  "⊇": "&supe;",
  "⊕": "&oplus;",
  "⊗": "&otimes;",
  "⊥": "&perp;",
  "α": "&alpha;",
  "β": "&beta;",
  "γ": "&gamma;",
  "δ": "&delta;",
  "ε": "&epsilon;",
  "ζ": "&zeta;",
  "η": "&eta;",
  "θ": "&theta;",
  "ι": "&iota;",
  "κ": "&kappa;",
  "λ": "&lambda;",
  "μ": "&mu;",
  "ν": "&nu;",
  "ξ": "&xi;",
  "ο": "&omicron;",
  "π": "&pi;",
  "ρ": "&rho;",
  "σ": "&sigma;",
  "τ": "&tau;",
  "υ": "&upsilon;",
  "φ": "&phi;",
  "χ": "&chi;",
  "ψ": "&psi;",
  "ω": "&omega;",
  "Α": "&Alpha;",
  "Β": "&Beta;",
  "Γ": "&Gamma;",
  "Δ": "&Delta;",
  "Ε": "&Epsilon;",
  "Ζ": "&Zeta;",
  "Η": "&Eta;",
  "Θ": "&Theta;",
  "Ι": "&Iota;",
  "Κ": "&Kappa;",
  "Λ": "&Lambda;",
  "Μ": "&Mu;",
  "Ν": "&Nu;",
  "Ξ": "&Xi;",
  "Ο": "&Omicron;",
  "Π": "&Pi;",
  "Ρ": "&Rho;",
  "Σ": "&Sigma;",
  "Τ": "&Tau;",
  "Υ": "&Upsilon;",
  "Φ": "&Phi;",
  "Χ": "&Chi;",
  "Ψ": "&Psi;",
  "Ω": "&Omega;"
};

// Reverse lookup
export const reverseEntities: Record<string, string> = {};
for (const [char, entity] of Object.entries(namedEntities)) {
  reverseEntities[entity.slice(1, -1)] = char;
}

export function encodeHtml(input: string): string {
  return input.replace(/[\u00A0-\uFFFF<>&"'`]/g, (ch) => {
    if (namedEntities[ch]) {
      return namedEntities[ch];
    }
    return `&#x${ch.charCodeAt(0).toString(16).toUpperCase()};`;
  });
}
